### ISSUE TITLE
NodeJS client library

### ISSUE THREAD

**Issue by eduardoweiland** [ablator/ablator#106]
I have a NodeJS project and I was thinking about using ablator for feature toggling. I know I can just call the API directly, but having a client library is very helpful. I can work on a client for NodeJS, I just need some directions. Is a new client library wanted? Should I create it as my own repo or would you like to have it in this organization? And what should be it's name?

Thanks for your good work on this project.

**Comment by winsmith** [comment]
Hi Eduardo,

That's awesome, thanks for your interest! A NodeJS library would be most appreciated, and would be a great addition. 

If it were up to me, I'd like to include the NodeJS client in the ablator project, but I'll leave that decision to you. 

- If you create the project on your own github account, you'll have more freedom and control, but people will probably not associate your library as directly with ablator. 
- If you create the project in the ablator account, I'm asking that it will adhere to the project's code of conduct (nothing surprising: no racism, sexism, or such like), and it'll be more closely connected to the rest. 

As a name, the next name on my list is [Caroline Herschel](https://en.m.wikipedia.org/wiki/Caroline_Herschel), so I'm asking you to consider *herschel* as the project name.

**Comment by winsmith** [comment]
Here's some more technical detail about implementing clients

## API Endpoint

 Up until now, ablator's API endpoints were used to retrieve one availability at a time. Lots of people on HN asked me, however, to have one API endpoint that returns all Availabilities of one App instead, which is a great idea. See also #95 

Yesterday, I finished writing API v2, which includes exactly that. One endpoint, you give it a user and an app id, and it returns everything it knows about that app. So, please write against that API (which is at `v2/which/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/?`) as opposed to the old v1 API.

## Base URL

Since ablator lives either on http://ablator.space/ or self-hosted, please make sure users of the library can edit the base URL of the client, in order to use either a hosted or self-hosted ablator.

## Caching

If you want to implement caching, consider #77. Ablator will send cache headers with each response, which cause most URL Request libraries to manage their own cache, which means less work for you.

**Comment by eduardoweiland** [comment]
I would like to contribute to the project itself, so I think it would be great to create the repository in the Ablator organization. _herschel_ is a good name.

**Comment by winsmith** [comment]
Just invited you to the ablator/herschel repo :) have fun

**Comment by winsmith** [comment]
Aah forgot to mention: Feel free to contact me at winsmith@winsmith.de if you want to talk more :)

**Comment by eduardoweiland** [comment]
Thanks. I will probably start working on this project tomorrow.
